from enum import StrEnum


class DatasetKind(StrEnum):
    DEVELOPMENT = "DEVELOPMENT"
    VALIDATION = "VALIDATION"
    FORMAL = "FORMAL"
    GENERALIZATION = "GENERALIZATION"
    REPAIR_POOL = "REPAIR_POOL"
    REPAIR_EVALUATION = "REPAIR_EVALUATION"
    REPEATABILITY = "REPEATABILITY"


class AssetType(StrEnum):
    CANONICAL_CHARACTER = "CANONICAL_CHARACTER"
    PRODUCT_VIEW = "PRODUCT_VIEW"
    MATERIAL_REFERENCE = "MATERIAL_REFERENCE"
    CASE_BASE = "CASE_BASE"


class ReadinessStatus(StrEnum):
    PILOT_ONLY = "PILOT_ONLY"
    BLOCKED = "BLOCKED"
    PASS = "PASS"


class InteractionKind(StrEnum):
    MOUTH = "MOUTH"
    NEAR_MOUTH = "NEAR_MOUTH"
    HAND_HELD = "HAND_HELD"


class PoseZone(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class AttemptState(StrEnum):
    CREATED = "CREATED"
    PREPARED = "PREPARED"
    INFERENCE_STARTED = "INFERENCE_STARTED"
    INFERENCE_SUCCEEDED = "INFERENCE_SUCCEEDED"
    OUTPUT_PERSISTED = "OUTPUT_PERSISTED"
    OUTPUT_VALIDATING = "OUTPUT_VALIDATING"
    VALID_OUTPUT = "VALID_OUTPUT"
    RETRY_PENDING = "RETRY_PENDING"
    OUTPUT_VALIDATION_FAILED = "OUTPUT_VALIDATION_FAILED"
    SYSTEM_FAIL = "SYSTEM_FAIL"
    CANCELLED = "CANCELLED"


class FormalRunState(StrEnum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    REVIEW_PENDING = "REVIEW_PENDING"
    COMPLETED = "COMPLETED"
    INVALIDATED = "INVALIDATED"


class DatasetRunState(StrEnum):
    DRAFT = "DRAFT"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    INVALIDATED = "INVALIDATED"


class OutputValidationStatus(StrEnum):
    PENDING = "PENDING"
    VALIDATING = "VALIDATING"
    VALID_OUTPUT = "VALID_OUTPUT"
    VALIDATION_FAILED = "VALIDATION_FAILED"


class GateDecision(StrEnum):
    PASS = "PASS"
    CONDITIONAL = "CONDITIONAL"
    NO_GO = "NO_GO"


class EvidenceStatus(StrEnum):
    EVIDENCE_PENDING = "EVIDENCE_PENDING"
    READY = "READY"
    INVALID = "INVALID"


class ReviewDecision(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"


class CheckStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    BLOCKED = "BLOCKED"
